### PR TITLE
Emiya

### PR DESCRIPTION
**Pull request by iEmiya**
+ memory Leaks #86
+ delete all history

### CODE REVIEW

**Comment by kevingy** [comment]
I have two issues with "Thread Safety, Memory Leaks etc #86".

First, I thought these changes had already been merged by @Teun. Is that not the case?

Secondly, if these are the same changes as #86 and Teun did not merge them, there was a discussion on that issue that these changes might or might not be appropriate. It kinda looks like you took those changes verbatim, then updated the unit tests to address my original issue. Is that not the case?

**Comment by Teun** [comment]
Kevin,
I did integrate #86 some time ago. However, scanning these new commits
superficially on my phone, I do think there are some new fixes here. I will
do a proper review later this weekend and compare with the fixes already
done in #86.

OK?

Teun
Op 3 jan. 2015 15:27 schreef "Kevin Yochum" <notifications@github.com>:

**Comment by iEmiya** [comment]
As I understand it # 86 was not yet integrated.
The proposed changes have been made in correcting unit tests.
PS. Solution is used for more than two weeks.

**Comment by Teun** [comment]
OK. I was wrong: I never integrated that issue. There was an issue, but no pull request. Some of the related stuff was done by me in #85, but not hte changes now contributed by iEmiya. 
It will break backward compat, but not in a way that will harm real users. Unit test have been updated accordingly by iEmiya. Looks good.

One question: this pull request also updates the AssemblyVersion to reflect the current release number in NuGet. We haven't done that before. We do not keep the version number in source control. The number is configured in TeamCity and is autoincremented at each build. I will merge, but with the change in AssemblyInfo.

**Comment by Teun** [comment]
The built and tests have passed. I will push a new version of SimpleBrowser to NuGet. 0.5.61.0

**Comment by kevingy** [comment]
@iEmiya @Teun 

Yikes! This is a huge change - at least for me. I'm having to go through and change how I call ClearWindows() in 280+ scripts. Why should a SimpleBrowser user be required to call both ClearWindows() and Close() in order to free all resources? Is Close() sufficient? Why do I need both calls?

As I said in response to #86 , this may have been *a* change, but it probably wasn't *the* change.

**Comment by Teun** [comment]
I see. I was thinking of backward compatibility in behavior, which seemed a small change. I forgot to think about the more important backward compatibility of the API interface. I apologize. 

We can restore by adding the static method back and have it call ClearWindows on all known families of windows. Would that fix your situation? I think the change to Close is just to make sure that closed windows disappear from the list. You don't have to change anything.

**Comment by Teun** [comment]
I created a pull request for restoring backward compatibility. I had to rename the instance scooped method.

**Comment by iEmiya** [comment]
I find it difficult to answer quickly (during the day).
Thinking can analyze the code for two, three days.
But a revision code shown that the solution may return an error.

Does it make sense to keep all open pages and use them globally?
private static List<List<Browser>> _allContexts = new List<List<Browser>>();

**Comment by iEmiya** [comment]
@kevingy 
"Why should a SimpleBrowser user be required to call both ClearWindows() and Close() in order to free all resources? Is Close() sufficient? Why do I need both calls?"

As far as I'm concerned the discovery of a single page can lead to the discovery of several pages (internal Browser CreateChildBrowser (string name = null))
Who, when and how can call Close() to child? How do understand that there are children?
It turns out you need to regularly cause ClearWindows (), which is not always convenient and clear when and where the work in multi-threaded applications (wait for completion of multiple streams strange idea)

What idea is embedded in the ability to access all open pages?

**Pull request merged**
